export function buildOpenApiDocument() {
  return {
    openapi: '3.1.0',
    info: {
      title: 'erwin-gateway API',
      version: process.env.npm_package_version ?? '0.1.0',
      description: 'Internal NTKOH gateway API for app authentication, Twitch chat, EventSub fanout, Channel Points, Twitch data, health, and admin setup.'
    },
    servers: [{ url: '/', description: 'Current erwin-gateway origin' }],
    tags: [
      { name: 'Health' },
      { name: 'Apps' },
      { name: 'Chat' },
      { name: 'Channel Points' },
      { name: 'Twitch Data' },
      { name: 'Twitch EventSub' },
      { name: 'Admin' },
      { name: 'Docs' }
    ],
    components: {
      securitySchemes: {
        appApiKey: { type: 'http', scheme: 'bearer', description: 'App API key generated by an admin. Raw key is shown once and stored only as a hash.' },
        adminApiKey: { type: 'apiKey', in: 'header', name: 'X-Admin-API-Key', description: 'Internal admin API key for admin routes.' }
      },
      schemas: {
        Error: { type: 'object', properties: { error: { type: 'string' }, code: { type: 'string' }, details: {}, twitchStatus: { type: 'integer' }, twitchErrorExcerpt: { type: 'string' }, issues: { type: 'array', items: {} } }, required: ['error'] },
        Health: { type: 'object', properties: { service: { const: 'erwin-gateway' }, status: { enum: ['healthy', 'ready', 'degraded'] }, timestamp: { type: 'string', format: 'date-time' }, uptimeSeconds: { type: 'number' }, build: { type: 'object' }, checks: { type: 'object' } }, required: ['service', 'status', 'timestamp'] },
        AppIdentity: { type: 'object', properties: { id: { type: 'string' }, name: { type: 'string' }, slug: { type: 'string' }, enabled: { type: 'boolean' }, permissions: { type: 'array', items: { type: 'string' } } } },
        ChatMessageRequest: { type: 'object', required: ['message', 'idempotency_key'], properties: { channel_id: { type: 'string' }, broadcaster_user_id: { type: 'string' }, message: { type: 'string', maxLength: 500 }, reply_parent_message_id: { type: 'string' }, idempotency_key: { type: 'string', minLength: 8, maxLength: 200 }, for_source_only: { type: 'boolean', default: true }, priority: { type: 'integer', minimum: -100, maximum: 100 } } },
        RewardRequest: { type: 'object', required: ['title'], properties: { channel_id: { type: 'string' }, title: { type: 'string' }, prompt: { type: 'string' }, cost: { type: 'integer' }, enabled: { type: 'boolean' }, background_color: { type: 'string' }, is_user_input_required: { type: 'boolean' }, max_per_stream: { type: 'integer' }, max_per_user_per_stream: { type: 'integer' }, global_cooldown_seconds: { type: 'integer' } } }
      }
    },
    paths: {
      '/openapi.json': { get: { tags: ['Docs'], summary: 'OpenAPI document', responses: { '200': { description: 'OpenAPI 3.1 JSON document' } } } },
      '/docs': { get: { tags: ['Docs'], summary: 'Interactive API docs', responses: { '200': { description: 'Swagger UI documentation page' } } } },
      '/api/v1/health/live': { get: { tags: ['Health'], summary: 'Liveness health check', responses: { '200': { description: 'Process is alive', content: { 'application/json': { schema: { $ref: '#/components/schemas/Health' } } } } } } },
      '/api/v1/health/ready': { get: { tags: ['Health'], summary: 'Readiness health check', responses: { '200': { description: 'Ready' }, '503': { description: 'Database, migration, worker, or Twitch setup degraded' } } } },
      '/api/v1/health/deep': { get: { tags: ['Health'], summary: 'Deep operational health with Twitch scopes, EventSub, queues, Channel Points, and dead-letter diagnostics', responses: { '200': { description: 'Healthy' }, '503': { description: 'Degraded' } } } },
      '/api/v1/me': { get: { tags: ['Apps'], security: [{ appApiKey: [] }], summary: 'Return authenticated app identity and permissions', responses: { '200': { description: 'Authenticated app' }, '401': { description: 'Missing, invalid, or revoked API key' } } } },
      '/api/v1/chat/messages': { post: { tags: ['Chat'], security: [{ appApiKey: [] }], summary: 'Queue an outgoing Twitch chat message with idempotency', requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/ChatMessageRequest' } } } }, responses: { '202': { description: 'Queued or duplicate existing message returned' }, '409': { description: 'Idempotency key reused with different parameters' } } } },
      '/api/v1/chat/messages/{messageId}': { get: { tags: ['Chat'], security: [{ appApiKey: [] }], summary: 'Get outgoing chat message status', parameters: [{ name: 'messageId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], responses: { '200': { description: 'Message status' }, '404': { description: 'Not found' } } } },
      '/api/v1/events': { get: { tags: ['Apps'], security: [{ appApiKey: [] }], summary: 'List gateway events visible to the app', parameters: [{ name: 'type', in: 'query', schema: { type: 'string' } }, { name: 'limit', in: 'query', schema: { type: 'integer' } }], responses: { '200': { description: 'Events' } } } },
      '/api/v1/channel-points/rewards': { get: { tags: ['Channel Points'], security: [{ appApiKey: [] }], summary: 'List Channel Point rewards' }, post: { tags: ['Channel Points'], security: [{ appApiKey: [] }], summary: 'Create an app-owned Channel Point reward', requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/RewardRequest' } } } }, responses: { '201': { description: 'Created reward' }, '403': { description: 'Missing permission' } } } },
      '/api/v1/channel-points/rewards/{rewardId}': { get: { tags: ['Channel Points'], security: [{ appApiKey: [] }], summary: 'Get reward' }, patch: { tags: ['Channel Points'], security: [{ appApiKey: [] }], summary: 'Update a reward owned by this app' }, delete: { tags: ['Channel Points'], security: [{ appApiKey: [] }], summary: 'Delete a reward owned by this app' } },
      '/api/v1/channel-points/rewards/{rewardId}/adopt': { post: { tags: ['Channel Points'], security: [{ appApiKey: [] }], summary: 'Adopt/bind an existing manageable reward to the authenticated app' } },
      '/api/v1/channel-points/rewards/{rewardId}/release': { post: { tags: ['Channel Points'], security: [{ appApiKey: [] }], summary: 'Release app ownership without deleting the Twitch reward' } },
      '/api/v1/channel-points/redemptions': { get: { tags: ['Channel Points'], security: [{ appApiKey: [] }], summary: 'List redemptions' } },
      '/api/v1/channel-points/redemptions/{redemptionId}/status': { post: { tags: ['Channel Points'], security: [{ appApiKey: [] }], summary: 'Fulfill or cancel an app-owned redemption' } },
      '/api/v1/subscriptions': { get: { tags: ['Twitch Data'], security: [{ appApiKey: [] }], summary: 'List subscription events/backfill rows' } },
      '/api/v1/subscriptions/backfill': { post: { tags: ['Twitch Data'], security: [{ appApiKey: [] }], summary: 'Run subscription backfill' } },
      '/api/v1/bits/leaderboard': { get: { tags: ['Twitch Data'], security: [{ appApiKey: [] }], summary: 'Read Bits leaderboard/cache' } },
      '/api/v1/bits/backfill': { post: { tags: ['Twitch Data'], security: [{ appApiKey: [] }], summary: 'Run Bits backfill' } },
      '/api/v1/streams/current': { get: { tags: ['Twitch Data'], security: [{ appApiKey: [] }], summary: 'Current stream status' } },
      '/api/v1/channels/{channelId}/profile': { get: { tags: ['Twitch Data'], security: [{ appApiKey: [] }], summary: 'Broadcaster/channel profile' } },
      '/api/v1/channels/{channelId}/schedule': { get: { tags: ['Twitch Data'], security: [{ appApiKey: [] }], summary: 'Channel stream schedule' } },
      '/webhooks/twitch/eventsub': { post: { tags: ['Twitch EventSub'], summary: 'Twitch EventSub webhook callback; verifies raw-body HMAC signature, handles challenge/notification/revocation, and deduplicates message IDs', responses: { '200': { description: 'Challenge response' }, '204': { description: 'Notification/revocation accepted or duplicate ignored' }, '403': { description: 'Invalid Twitch signature' } } } },
      '/api/admin/shell': { get: { tags: ['Admin'], security: [{ adminApiKey: [] }], summary: 'Admin UI shell metadata' } },
      '/api/admin/apps': { get: { tags: ['Admin'], security: [{ adminApiKey: [] }], summary: 'List registered apps' }, post: { tags: ['Admin'], security: [{ adminApiKey: [] }], summary: 'Register an app' } },
      '/api/admin/apps/{id}/keys': { post: { tags: ['Admin'], security: [{ adminApiKey: [] }], summary: 'Generate an app API key; raw key is shown once' } },
      '/api/admin/twitch/setup/status': { get: { tags: ['Admin'], security: [{ adminApiKey: [] }], summary: 'Twitch OAuth/scope setup status' } },
      '/api/admin/twitch/eventsub/status': { get: { tags: ['Admin'], security: [{ adminApiKey: [] }], summary: 'EventSub subscription diagnostics' } }
    }
  };
}
